## np.full


In [3]:
import numpy as np

In [4]:
n1 = np.full((2,3),4)
print(n1)

[[4 4 4]
 [4 4 4]]


In [5]:
## random parameters: start stop and number of element

In [7]:
n2 = np.random.randint(1,100,5)
print(n2)
#this prints 5 random integers between 1 and 100

[28 38 87 21 86]


In [11]:
#columnstack
n3 = np.array([2,3,4,5])
n4 = np.array([6,7,8,9])
np.column_stack((n3,n4))


array([[2, 6],
       [3, 7],
       [4, 8],
       [5, 9]])

## intersection and difference methods

In [12]:
v1 = np.array([12,14,16,18,20])
v2 = np.array([10,20,30,40,50])

In [14]:
np.intersect1d(v1,v2)
#prints intersect of v1 and v2

array([20])

In [15]:
np.setdiff1d(v1,v2)
#diff of v2 from v1

array([12, 14, 16, 18])

In [16]:
np.setdiff1d(v2,v1)

array([10, 30, 40, 50])

### questions

In [17]:
#create a 1d array from 0 to 9
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:

b1= np.ones((3,3),dtype = 'bool')
print(b1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [27]:
#craete a 3x3 array with all true
c= np.full((3,3),True,dtype='bool')
print(c)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [32]:
#extract all odd numbs from an array
d = np.arange(1,20)
c = d[d%2==1]
print(c)

[ 1  3  5  7  9 11 13 15 17 19]


In [37]:
#replace all odd numbers with -1
d = np.arange(1,10)
c = np.where((d % 2 == 0),d,-1)
print(c)

[-1  2 -1  4 -1  6 -1  8 -1]


In [38]:
#or 
d = np.arange(1,10)
d[d%2==0] = -1
print(d)

[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19]


In [53]:
#convert  a 1d array to 2d array with 2 rows
arr = np.arange(10)
print(arr)
e2 = arr.reshape(2,5)
print(e2)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [56]:
#create this pattern(1,1,1,2,,2,2,,3,3,3)
a = np.array([1,2,3])
np.r_[(np.repeat(a,3),np.tile(a,3))]
#r_ is use to concanate any number of array slicies along the row axis
#np.tile use to repeat an aray based on the number of times sppecified


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [57]:
np.tile(a,4)
   

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## advanced indexing

In [58]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
#to get 3 and 7
b[[0,2],[2,0]]
#the first list is the row of both 3 and 7 and the second is their column

array([3, 7])

In [59]:
t = np.array([[1,2],[3,4],[5,6],[7,8]])
#to get 4,2,7
t[[0,1,3],[1,1,0]]

array([2, 4, 7])

In [61]:
t[[0,3,1],[1,0,1]]

array([2, 7, 4])

In [62]:
t[[0,1,2],[0,1,0]]

array([1, 4, 5])

In [64]:
r = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
#to get 0,2 and 9 11
rows = np.array([[0,0],[3,3]])
# as 0,2 are in first row and 10 11 are on 3 row
column = np.array([[0,2],[1,2]])
y = r[rows,column]
print(y)

[[ 0  2]
 [10 11]]


In [65]:
#more examples
#2,7 and 8,10
rows = np.array([[0,2],[2,3]])
column = np.array([[2,1],[2,1]])
y = r[rows,column]
print(y)

[[ 2  7]
 [ 8 10]]
