In [1]:
import numpy as np


In [2]:
a = np.array([1,3,5])
print(a)

[1 3 5]


In [3]:
b = np.array([[2,4,6],[6,7,8]])
print(b)

[[2 4 6]
 [6 7 8]]


In [4]:
#how to get the dimension of an array
a.ndim

1

In [5]:
#we can also use shape but this tells us the numb of rows and column
b.shape

(2, 3)

In [6]:
a.dtype

dtype('int32')

In [7]:
a.size

3

In [8]:
b.itemsize

4

In [9]:
#acessing and changing specific elements rows and columns
c = np.array([[2,3,4,5,6,7,8],[11,12,13,14,15,16,17]])
print(c)

[[ 2  3  4  5  6  7  8]
 [11 12 13 14 15 16 17]]


In [10]:
c.shape

(2, 7)

In [11]:
#to print the data 13
c[1,2]

13

In [12]:
c[:,4]

array([ 6, 15])

In [13]:
#to get a specific row and all column
c[0,:]

array([2, 3, 4, 5, 6, 7, 8])

In [14]:
c[0,(2,4)]

array([4, 6])

In [15]:
#to change an element
c[1,2]= 20
print(c)

[[ 2  3  4  5  6  7  8]
 [11 12 20 14 15 16 17]]


In [16]:
#to change more than one element this change the element in all the second coloumn of all the rows
c[:,2] = 5
print(c)

[[ 2  3  5  5  6  7  8]
 [11 12  5 14 15 16 17]]


In [17]:
#to inset different element
c[:,2] = [5,7]
print(c)

[[ 2  3  5  5  6  7  8]
 [11 12  7 14 15 16 17]]


In [18]:
#3d array
d = np.array([[[3,4],[5,6]],[[8,9],[11,12]]])
print(d)

[[[ 3  4]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]


In [19]:
#to get an element from array d
d[:,1,1]

array([ 6, 12])

In [20]:
d[:,0,0]

array([3, 8])

In [21]:
#all the rows in first column
d[:,:,0]

array([[ 3,  5],
       [ 8, 11]])

In [22]:
d[1,(0,1)]

array([[ 8,  9],
       [11, 12]])

In [23]:
#or
d[0,:,:]

array([[3, 4],
       [5, 6]])

In [24]:
d[:,1,:]

array([[ 5,  6],
       [11, 12]])

# initializing different types of arrays



In [25]:
#all zeroes matrics
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
#for 2dimensional
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
#all ones matix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [28]:
#for any other number
np.full((2,3),23,dtype = 'float')

array([[23., 23., 23.],
       [23., 23., 23.]])

In [29]:
#random demcimalnumbers
np.random.rand(4,3)
#this prints a 4 x 3 matix with random decimal numbers between 0 and 1


array([[0.13752776, 0.75919155, 0.09365473],
       [0.29719807, 0.13190132, 0.53991292],
       [0.64233139, 0.47750298, 0.97122158],
       [0.21863997, 0.41507092, 0.22987793]])

In [30]:
np.random.rand(4,3,2)

array([[[0.91593528, 0.78802732],
        [0.50730363, 0.02182554],
        [0.6681612 , 0.59288933]],

       [[0.54161356, 0.63289362],
        [0.70711641, 0.87683629],
        [0.46962738, 0.34483648]],

       [[0.02947092, 0.80693307],
        [0.50683545, 0.4430976 ],
        [0.61358993, 0.41386407]],

       [[0.15033824, 0.56616021],
        [0.22274349, 0.2491197 ],
        [0.08567864, 0.93386295]]])

##random integer values


In [31]:
np.random.randint(12,71,size =(3,3))
#this  prints random integers between 12 to 71 in a 3 by 3 matrix format 

array([[14, 29, 15],
       [20, 19, 45],
       [15, 42, 37]])

In [32]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
s = np.ones((5,5),dtype = 'int')
print(s)
z = np.zeros((3,3))
print(z)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
z[1,1]=9
print(z)

s[1:4,1:4] = z
print(s)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## becarefule when copying arrays

In [35]:
a = np.array([12,20,34])
b = a
b
#b has same value as a
b[0] =  24
b
#the value of b is changed to 34 same as the value of a

array([24, 20, 34])

In [36]:
ab = np.array([24, 20, 34])
b = ab.copy()
b
#b is now a copy of a
b[0] =  34
b

#copy attribute is use to prevent the error seen above

array([34, 20, 34])

##mathematics


In [37]:
ab + 2

array([26, 22, 36])

In [38]:
ab - 2

array([22, 18, 32])

In [39]:
ab * 3

array([ 72,  60, 102])

In [40]:
ab/2

array([12., 10., 17.])

In [41]:
ab**2

array([ 576,  400, 1156])

In [42]:
#sin
np.sin(ab)

array([-0.90557836,  0.91294525,  0.52908269])

In [43]:
np.cos(ab)

array([ 0.42417901,  0.40808206, -0.84857027])

#linear algeabra

In [44]:
d = np.ones((2,3))
print(d)
t = np.full((3,2),2)
print(t)
#to multiply 2 matix
np.matmul(d,t)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [45]:
c[-1]
#this prints all the elements in the last row

array([11, 12,  7, 14, 15, 16, 17])

In [46]:
 #our to iterate an array
x = np.array([[6,7,8],[1,2,3],[9,4,3]])
for cell in x:
    print(cell)

[6 7 8]
[1 2 3]
[9 4 3]


In [47]:
#to flatten the list
for cell in x.flat:
    print(cell)

6
7
8
1
2
3
9
4
3


In [48]:
#stacking 2 arrays
v = np.arange(6).reshape(3,2)
#this creates 3 by 2 an arrray fromrange 0 to 6 
print(v)
n = np.arange(6,12).reshape(3,2)

n

[[0 1]
 [2 3]
 [4 5]]


array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [49]:
#to stack our arrays
j = np.vstack((v,n))
j
#vstack - vertical stacking 


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [50]:
#hstack horizontal sdtacking
j = np.hstack((v,n))
j

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [51]:
t = np.arange(30).reshape(2,15)
t

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [52]:
#to split an array using hsplit-horizontal spliting
result = np.hsplit(t,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [53]:
result = np.vsplit(t,2)
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

## sorting of arrays

In [54]:
sorted_array =  np.sort(x)
print(sorted_array)

[[6 7 8]
 [1 2 3]
 [3 4 9]]


#to sort by column 
sorted_array =

np.sort(x,axis = 0)
print(sorted_array)

In [55]:
#to by rows which is the default
sorted_array =  np.sort(x,axis = -1)
print(sorted_array)

[[6 7 8]
 [1 2 3]
 [3 4 9]]


In [56]:
##to calculate the dot product
#this gives the total multiplication value of 2 array

In [57]:
l1 = np.array([2,3,4])
l2 = np.array([5,6,7])
dot = np.dot(l1,l2)
print(dot)

56


In [58]:
set = np.array([[2,4],[5,7],[6,8]])
print(set)
#this prints the element which are greater than 4,if it is less than 4 the element is replaced by 0
vr = np.where(set > 4, set ,0)
print(vr)

[[2 4]
 [5 7]
 [6 8]]
[[0 0]
 [5 7]
 [6 8]]


In [59]:
#single array operations

In [60]:
array_a = np.array([[1,2],[3,4]])
array_b = np.array([[2,2],[6,6]])
print(array_a.sum())

10


In [61]:
#to sum along an axis one for row zero for column
print(array_a.sum(axis = 0))

[4 6]


In [62]:
print(array_a.sum(axis = 1))
#along the rows

[3 7]


In [63]:
print(array_a.cumsum())
print(array_a.prod())
print(array_a.cumprod())
#note we can apply axis to any of this

[ 1  3  6 10]
24
[ 1  2  6 24]


## two array math

In [66]:
print(array_a + array_b)
print(array_a - array_b)
print(array_a * array_b)
print(array_a  / array_b)

[[ 3  4]
 [ 9 10]]
[[-1  0]
 [-3 -2]]
[[ 2  4]
 [18 24]]
[[0.5        1.        ]
 [0.5        0.66666667]]


In [67]:
#vector product
print(np.dot(array_a,array_b))
#[[1*2+2*6, 1*2+2*6],[3*2+4*6,3*2+4*6]]  

[[14 14]
 [30 30]]


In [68]:
array_c =np.array([[1,2,3],[4,5,6],[7,8,9]])
array_d =np.array([[2,2,2],[3,4,5],[6,7,8]])
print(array_c.sum(axis = 0))
print(array_c.sum(axis = 1))

[12 15 18]
[ 6 15 24]


In [70]:
print(array_c)
print(array_c.ptp(axis = 1))

#takes maxium number and subtract the minimumvalue for it along each row as axis = 1

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 2 2]


In [71]:
print(array_c)
print(array_c.ptp(axis = 0))
#for column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[6 6 6]


In [72]:
print(array_c)
print(array_c.ptp())
#if the axis is not specified it becomes highest num minus lowest num

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8


In [74]:
print(array_c.max())
print(array_c.mean())
print(array_c.min())

9
5.0
1


In [75]:
#power
print(np.power(array_c,array_d))
#first value is the base second is the exponent

[[       1        4        9]
 [      64      625     7776]
 [  117649  2097152 43046721]]


In [79]:
array_e = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(array_e + array_d + array_c)
print(array_e * array_d * array_c)
print(array_e - array_d - array_c)

[[ 4  5  6]
 [ 9 11 13]
 [16 18 20]]
[[  2   4   6]
 [ 24  40  60]
 [126 168 216]]
[[ -2  -3  -4]
 [ -5  -7  -9]
 [-10 -12 -14]]


### Broadcasting
#this allows us to do numerical operations on array of different shapes

In [82]:
array_x = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
array_y = np.array([0,1,2,3])
array_z = np.array([[1],[2],[3]])
print(array_x + array_y )
print(array_x + array_z)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
[[2 2 2 2]
 [4 4 4 4]
 [6 6 6 6]]


In [85]:
#more on broadcasting
array_r = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_u = np.array([3,2,1])
print(array_r +array_u)
#this adds 3 to all first element 2 to the second and 3 to the last
#anpther method is matchin the num of columns
array_i = np.array([[3],[2],[1]])
print(array_r +array_i)

[[ 4  4  4]
 [ 7  7  7]
 [10 10 10]]
[[ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]


In [86]:
c = np.array(ones,5)
print(c)

NameError: name 'ones' is not defined