In [3]:
import numpy as np

In [4]:
#n dimensional homogenous array
np.array([2,3,4,5])

array([2, 3, 4, 5])

In [5]:
#lets import data from scikit learn to work with

from sklearn.datasets import load_wine

In [6]:
data_bunch = load_wine()

In [7]:
data_bunch

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [8]:
wine_data_ar = data_bunch['data']

In [9]:
wine_data_ar

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [10]:
#to acess the first item on our list
wine_data_ar[10]

array([1.41e+01, 2.16e+00, 2.30e+00, 1.80e+01, 1.05e+02, 2.95e+00,
       3.32e+00, 2.20e-01, 2.38e+00, 5.75e+00, 1.25e+00, 3.17e+00,
       1.51e+03])

In [11]:
#the shape methods tells us the type of array  and the number of items in the rows amd columns
wine_data_ar.shape

(178, 13)

In [12]:
##maths in numpy
alcohol = wine_data_ar[:,0]


In [13]:
feature_names = data_bunch['feature_names']

In [14]:
feature_names


['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [15]:
## in numpy while indexing the first number represent the rows and the second reprsent the column
#we use : to print all the rows of data in the specified column
wine_data_ar[: , 0]
#this print all the rows in the first column

array([14.23, 13.2 , 13.16, 14.37, 13.24, 14.2 , 14.39, 14.06, 14.83,
       13.86, 14.1 , 14.12, 13.75, 14.75, 14.38, 13.63, 14.3 , 13.83,
       14.19, 13.64, 14.06, 12.93, 13.71, 12.85, 13.5 , 13.05, 13.39,
       13.3 , 13.87, 14.02, 13.73, 13.58, 13.68, 13.76, 13.51, 13.48,
       13.28, 13.05, 13.07, 14.22, 13.56, 13.41, 13.88, 13.24, 13.05,
       14.21, 14.38, 13.9 , 14.1 , 13.94, 13.05, 13.83, 13.82, 13.77,
       13.74, 13.56, 14.22, 13.29, 13.72, 12.37, 12.33, 12.64, 13.67,
       12.37, 12.17, 12.37, 13.11, 12.37, 13.34, 12.21, 12.29, 13.86,
       13.49, 12.99, 11.96, 11.66, 13.03, 11.84, 12.33, 12.7 , 12.  ,
       12.72, 12.08, 13.05, 11.84, 12.67, 12.16, 11.65, 11.64, 12.08,
       12.08, 12.  , 12.69, 12.29, 11.62, 12.47, 11.81, 12.29, 12.37,
       12.29, 12.08, 12.6 , 12.34, 11.82, 12.51, 12.42, 12.25, 12.72,
       12.22, 11.61, 11.46, 12.52, 11.76, 11.41, 12.08, 11.03, 11.82,
       12.42, 12.77, 12.  , 11.45, 11.56, 12.42, 13.05, 11.87, 12.07,
       12.43, 11.79,

In [16]:
#to print data for 2 or more colums
wine_data_ar[:,(0,4)]
#this prints all the rows in first column  and 4th column

array([[ 14.23, 127.  ],
       [ 13.2 , 100.  ],
       [ 13.16, 101.  ],
       [ 14.37, 113.  ],
       [ 13.24, 118.  ],
       [ 14.2 , 112.  ],
       [ 14.39,  96.  ],
       [ 14.06, 121.  ],
       [ 14.83,  97.  ],
       [ 13.86,  98.  ],
       [ 14.1 , 105.  ],
       [ 14.12,  95.  ],
       [ 13.75,  89.  ],
       [ 14.75,  91.  ],
       [ 14.38, 102.  ],
       [ 13.63, 112.  ],
       [ 14.3 , 120.  ],
       [ 13.83, 115.  ],
       [ 14.19, 108.  ],
       [ 13.64, 116.  ],
       [ 14.06, 126.  ],
       [ 12.93, 102.  ],
       [ 13.71, 101.  ],
       [ 12.85,  95.  ],
       [ 13.5 ,  96.  ],
       [ 13.05, 124.  ],
       [ 13.39,  93.  ],
       [ 13.3 ,  94.  ],
       [ 13.87, 107.  ],
       [ 14.02,  96.  ],
       [ 13.73, 101.  ],
       [ 13.58, 106.  ],
       [ 13.68, 104.  ],
       [ 13.76, 132.  ],
       [ 13.51, 110.  ],
       [ 13.48, 100.  ],
       [ 13.28, 110.  ],
       [ 13.05,  98.  ],
       [ 13.07,  98.  ],
       [ 14.22, 128.  ],


In [17]:
wine_data_ar[:,0].shape
#this returns a one dimension array


(178,)

In [18]:
wine_data_ar[:,(0,4)].shape
##this returns a two dimension array as we are returning 2 columns
#first value rep number of rows second is the number of column  

(178, 2)

In [19]:
#to slect certian rows of the data
wine_data_ar[:10,(0,4)]


array([[ 14.23, 127.  ],
       [ 13.2 , 100.  ],
       [ 13.16, 101.  ],
       [ 14.37, 113.  ],
       [ 13.24, 118.  ],
       [ 14.2 , 112.  ],
       [ 14.39,  96.  ],
       [ 14.06, 121.  ],
       [ 14.83,  97.  ],
       [ 13.86,  98.  ]])

In [20]:
wine_data_ar[::2,(0,4)]


array([[ 14.23, 127.  ],
       [ 13.16, 101.  ],
       [ 13.24, 118.  ],
       [ 14.39,  96.  ],
       [ 14.83,  97.  ],
       [ 14.1 , 105.  ],
       [ 13.75,  89.  ],
       [ 14.38, 102.  ],
       [ 14.3 , 120.  ],
       [ 14.19, 108.  ],
       [ 14.06, 126.  ],
       [ 13.71, 101.  ],
       [ 13.5 ,  96.  ],
       [ 13.39,  93.  ],
       [ 13.87, 107.  ],
       [ 13.73, 101.  ],
       [ 13.68, 104.  ],
       [ 13.51, 110.  ],
       [ 13.28, 110.  ],
       [ 13.07,  98.  ],
       [ 13.56, 117.  ],
       [ 13.88, 101.  ],
       [ 13.05, 107.  ],
       [ 14.38, 102.  ],
       [ 14.1 , 103.  ],
       [ 13.05,  92.  ],
       [ 13.82, 111.  ],
       [ 13.74, 118.  ],
       [ 14.22, 118.  ],
       [ 13.72, 108.  ],
       [ 12.33, 101.  ],
       [ 13.67,  94.  ],
       [ 12.17, 104.  ],
       [ 13.11,  78.  ],
       [ 13.34, 110.  ],
       [ 12.29, 103.  ],
       [ 13.49,  87.  ],
       [ 11.96, 101.  ],
       [ 13.03,  86.  ],
       [ 12.33, 136.  ],


In [21]:
alcohol

array([14.23, 13.2 , 13.16, 14.37, 13.24, 14.2 , 14.39, 14.06, 14.83,
       13.86, 14.1 , 14.12, 13.75, 14.75, 14.38, 13.63, 14.3 , 13.83,
       14.19, 13.64, 14.06, 12.93, 13.71, 12.85, 13.5 , 13.05, 13.39,
       13.3 , 13.87, 14.02, 13.73, 13.58, 13.68, 13.76, 13.51, 13.48,
       13.28, 13.05, 13.07, 14.22, 13.56, 13.41, 13.88, 13.24, 13.05,
       14.21, 14.38, 13.9 , 14.1 , 13.94, 13.05, 13.83, 13.82, 13.77,
       13.74, 13.56, 14.22, 13.29, 13.72, 12.37, 12.33, 12.64, 13.67,
       12.37, 12.17, 12.37, 13.11, 12.37, 13.34, 12.21, 12.29, 13.86,
       13.49, 12.99, 11.96, 11.66, 13.03, 11.84, 12.33, 12.7 , 12.  ,
       12.72, 12.08, 13.05, 11.84, 12.67, 12.16, 11.65, 11.64, 12.08,
       12.08, 12.  , 12.69, 12.29, 11.62, 12.47, 11.81, 12.29, 12.37,
       12.29, 12.08, 12.6 , 12.34, 11.82, 12.51, 12.42, 12.25, 12.72,
       12.22, 11.61, 11.46, 12.52, 11.76, 11.41, 12.08, 11.03, 11.82,
       12.42, 12.77, 12.  , 11.45, 11.56, 12.42, 13.05, 11.87, 12.07,
       12.43, 11.79,

In [22]:
np.average(alcohol)

13.00061797752809

In [23]:
np.mean(alcohol)

13.00061797752809

In [24]:
np.min(alcohol)

11.03

In [25]:
np.max(alcohol)

14.83

In [26]:
np.std(alcohol)

0.8095429145285168

In [27]:
arr = [[2,3,4],[4,3,7]]

In [28]:
np.square(arr)
#square function is an example of element wise function

array([[ 4,  9, 16],
       [16,  9, 49]])

In [29]:
#filtering of data in numpy
#using boolean mask
alcohol_under13 = alcohol < 13

In [30]:
alcohol_under13

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True, False,
        True,  True,  True, False,  True, False,  True,  True, False,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,

In [31]:
#to filter our data so the rows return would only that which is less than 13
wine_data_ar[alcohol_under13]
#this returns all the rows that  meets the conndition and all the column


array([[1.293e+01, 3.800e+00, 2.650e+00, ..., 1.030e+00, 3.520e+00,
        7.700e+02],
       [1.285e+01, 1.600e+00, 2.520e+00, ..., 1.090e+00, 3.630e+00,
        1.015e+03],
       [1.237e+01, 9.400e-01, 1.360e+00, ..., 1.050e+00, 1.820e+00,
        5.200e+02],
       ...,
       [1.282e+01, 3.370e+00, 2.300e+00, ..., 7.200e-01, 1.750e+00,
        6.850e+02],
       [1.220e+01, 3.030e+00, 2.320e+00, ..., 6.600e-01, 1.830e+00,
        5.100e+02],
       [1.277e+01, 2.390e+00, 2.280e+00, ..., 5.700e-01, 1.630e+00,
        4.700e+02]])

In [32]:
wine_data_ar[alcohol_under13,0]
#this returns all the rows that  meets the conndition and the first column


array([12.93, 12.85, 12.37, 12.33, 12.64, 12.37, 12.17, 12.37, 12.37,
       12.21, 12.29, 12.99, 11.96, 11.66, 11.84, 12.33, 12.7 , 12.  ,
       12.72, 12.08, 11.84, 12.67, 12.16, 11.65, 11.64, 12.08, 12.08,
       12.  , 12.69, 12.29, 11.62, 12.47, 11.81, 12.29, 12.37, 12.29,
       12.08, 12.6 , 12.34, 11.82, 12.51, 12.42, 12.25, 12.72, 12.22,
       11.61, 11.46, 12.52, 11.76, 11.41, 12.08, 11.03, 11.82, 12.42,
       12.77, 12.  , 11.45, 11.56, 12.42, 11.87, 12.07, 12.43, 11.79,
       12.37, 12.04, 12.86, 12.88, 12.81, 12.7 , 12.51, 12.6 , 12.25,
       12.53, 12.84, 12.93, 12.25, 12.87, 12.79, 12.58, 12.45, 12.36,
       12.85, 12.96, 12.82, 12.2 , 12.77])

In [33]:
wine_data_ar[alcohol_under13].shape


(86, 13)

In [34]:
magnesium = wine_data_ar[:,4]


In [35]:
magnesium

array([127., 100., 101., 113., 118., 112.,  96., 121.,  97.,  98., 105.,
        95.,  89.,  91., 102., 112., 120., 115., 108., 116., 126., 102.,
       101.,  95.,  96., 124.,  93.,  94., 107.,  96., 101., 106., 104.,
       132., 110., 100., 110.,  98.,  98., 128., 117.,  90., 101., 103.,
       107., 111., 102., 101., 103., 108.,  92.,  94., 111., 115., 118.,
       116., 118., 102., 108.,  88., 101., 100.,  94.,  87., 104.,  98.,
        78.,  78., 110., 151., 103.,  86.,  87., 139., 101.,  97.,  86.,
       112., 136., 101.,  86.,  86.,  78.,  85.,  94.,  99.,  90.,  88.,
        84.,  70.,  81.,  86.,  80.,  88.,  98., 162., 134.,  85.,  88.,
        88.,  97.,  88.,  98.,  86.,  85.,  90.,  80.,  84.,  92.,  94.,
       107.,  88., 103.,  88.,  84.,  85.,  86., 108.,  80.,  87.,  96.,
       119., 102.,  86.,  82.,  85.,  86.,  92.,  88.,  80., 122., 104.,
        98., 106.,  85.,  94.,  89.,  96.,  88., 101.,  96.,  89.,  97.,
        92., 112., 102.,  80.,  86.,  92., 113., 12

In [37]:
magnesium_value127_boolean = magnesium >120

In [38]:
combined_mask = magnesium_value127_boolean & alcohol_under13

In [39]:
wine_data_ar[combined_mask ][:,(0,4)]
#this gives all the data that appears all true in the first and fourth column when combined

array([[ 12.21, 151.  ],
       [ 12.99, 139.  ],
       [ 12.33, 136.  ],
       [ 12.47, 162.  ],
       [ 11.81, 134.  ],
       [ 12.86, 122.  ]])

In [40]:
combined_mask_or = magnesium_value127_boolean | alcohol_under13

In [41]:
wine_data_ar[combined_mask_or ][:,(0,4)]


array([[ 14.23, 127.  ],
       [ 14.06, 121.  ],
       [ 14.06, 126.  ],
       [ 12.93, 102.  ],
       [ 12.85,  95.  ],
       [ 13.05, 124.  ],
       [ 13.76, 132.  ],
       [ 14.22, 128.  ],
       [ 12.37,  88.  ],
       [ 12.33, 101.  ],
       [ 12.64, 100.  ],
       [ 12.37,  87.  ],
       [ 12.17, 104.  ],
       [ 12.37,  98.  ],
       [ 12.37,  78.  ],
       [ 12.21, 151.  ],
       [ 12.29, 103.  ],
       [ 12.99, 139.  ],
       [ 11.96, 101.  ],
       [ 11.66,  97.  ],
       [ 11.84, 112.  ],
       [ 12.33, 136.  ],
       [ 12.7 , 101.  ],
       [ 12.  ,  86.  ],
       [ 12.72,  86.  ],
       [ 12.08,  78.  ],
       [ 11.84,  94.  ],
       [ 12.67,  99.  ],
       [ 12.16,  90.  ],
       [ 11.65,  88.  ],
       [ 11.64,  84.  ],
       [ 12.08,  70.  ],
       [ 12.08,  81.  ],
       [ 12.  ,  86.  ],
       [ 12.69,  80.  ],
       [ 12.29,  88.  ],
       [ 11.62,  98.  ],
       [ 12.47, 162.  ],
       [ 11.81, 134.  ],
       [ 12.29,  85.  ],


In [44]:
np.where(alcohol < 12,'low alcohol','other')#if alcohol value is less than 12 it returns low alcohol else returns others

array(['other', 'other', 'other', 'other', 'other', 'other', 'other',
       'other', 'other', 'other', 'other', 'other', 'other', 'other',
       'other', 'other', 'other', 'other', 'other', 'other', 'other',
       'other', 'other', 'other', 'other', 'other', 'other', 'other',
       'other', 'other', 'other', 'other', 'other', 'other', 'other',
       'other', 'other', 'other', 'other', 'other', 'other', 'other',
       'other', 'other', 'other', 'other', 'other', 'other', 'other',
       'other', 'other', 'other', 'other', 'other', 'other', 'other',
       'other', 'other', 'other', 'other', 'other', 'other', 'other',
       'other', 'other', 'other', 'other', 'other', 'other', 'other',
       'other', 'other', 'other', 'other', 'low alcohol', 'low alcohol',
       'other', 'low alcohol', 'other', 'other', 'other', 'other',
       'other', 'other', 'low alcohol', 'other', 'other', 'low alcohol',
       'low alcohol', 'other', 'other', 'other', 'other', 'other',
       'low alcohol'

In [45]:
#to do multiple condtion
np.where(alcohol < 12 ,
        'low alcohol',
        np.where( alcohol > 14,'high alcohol',
                'moderate alcohol',
                )
        )
#nested if logic

array(['high alcohol', 'moderate alcohol', 'moderate alcohol',
       'high alcohol', 'moderate alcohol', 'high alcohol', 'high alcohol',
       'high alcohol', 'high alcohol', 'moderate alcohol', 'high alcohol',
       'high alcohol', 'moderate alcohol', 'high alcohol', 'high alcohol',
       'moderate alcohol', 'high alcohol', 'moderate alcohol',
       'high alcohol', 'moderate alcohol', 'high alcohol',
       'moderate alcohol', 'moderate alcohol', 'moderate alcohol',
       'moderate alcohol', 'moderate alcohol', 'moderate alcohol',
       'moderate alcohol', 'moderate alcohol', 'high alcohol',
       'moderate alcohol', 'moderate alcohol', 'moderate alcohol',
       'moderate alcohol', 'moderate alcohol', 'moderate alcohol',
       'moderate alcohol', 'moderate alcohol', 'moderate alcohol',
       'high alcohol', 'moderate alcohol', 'moderate alcohol',
       'moderate alcohol', 'moderate alcohol', 'moderate alcohol',
       'high alcohol', 'high alcohol', 'moderate alcohol', 'hi

In [46]:
#sorting in numpy by default our array is sorted in ascending order
np.sort(alcohol)

array([11.03, 11.41, 11.45, 11.46, 11.56, 11.61, 11.62, 11.64, 11.65,
       11.66, 11.76, 11.79, 11.81, 11.82, 11.82, 11.84, 11.84, 11.87,
       11.96, 12.  , 12.  , 12.  , 12.04, 12.07, 12.08, 12.08, 12.08,
       12.08, 12.08, 12.16, 12.17, 12.2 , 12.21, 12.22, 12.25, 12.25,
       12.25, 12.29, 12.29, 12.29, 12.29, 12.33, 12.33, 12.34, 12.36,
       12.37, 12.37, 12.37, 12.37, 12.37, 12.37, 12.42, 12.42, 12.42,
       12.43, 12.45, 12.47, 12.51, 12.51, 12.52, 12.53, 12.58, 12.6 ,
       12.6 , 12.64, 12.67, 12.69, 12.7 , 12.7 , 12.72, 12.72, 12.77,
       12.77, 12.79, 12.81, 12.82, 12.84, 12.85, 12.85, 12.86, 12.87,
       12.88, 12.93, 12.93, 12.96, 12.99, 13.03, 13.05, 13.05, 13.05,
       13.05, 13.05, 13.05, 13.07, 13.08, 13.11, 13.11, 13.16, 13.16,
       13.17, 13.17, 13.2 , 13.23, 13.24, 13.24, 13.27, 13.28, 13.29,
       13.3 , 13.32, 13.34, 13.36, 13.39, 13.4 , 13.4 , 13.41, 13.45,
       13.48, 13.48, 13.49, 13.49, 13.5 , 13.5 , 13.51, 13.52, 13.56,
       13.56, 13.58,

In [47]:
#to rverse the order of sorting
np.sort(alcohol)[::-1]
#this reverses the aray

array([14.83, 14.75, 14.39, 14.38, 14.38, 14.37, 14.34, 14.3 , 14.23,
       14.22, 14.22, 14.21, 14.2 , 14.19, 14.16, 14.13, 14.12, 14.1 ,
       14.1 , 14.06, 14.06, 14.02, 13.94, 13.9 , 13.88, 13.88, 13.87,
       13.86, 13.86, 13.84, 13.83, 13.83, 13.82, 13.78, 13.77, 13.76,
       13.75, 13.74, 13.73, 13.73, 13.72, 13.71, 13.71, 13.69, 13.68,
       13.67, 13.64, 13.63, 13.62, 13.58, 13.58, 13.56, 13.56, 13.52,
       13.51, 13.5 , 13.5 , 13.49, 13.49, 13.48, 13.48, 13.45, 13.41,
       13.4 , 13.4 , 13.39, 13.36, 13.34, 13.32, 13.3 , 13.29, 13.28,
       13.27, 13.24, 13.24, 13.23, 13.2 , 13.17, 13.17, 13.16, 13.16,
       13.11, 13.11, 13.08, 13.07, 13.05, 13.05, 13.05, 13.05, 13.05,
       13.05, 13.03, 12.99, 12.96, 12.93, 12.93, 12.88, 12.87, 12.86,
       12.85, 12.85, 12.84, 12.82, 12.81, 12.79, 12.77, 12.77, 12.72,
       12.72, 12.7 , 12.7 , 12.69, 12.67, 12.64, 12.6 , 12.6 , 12.58,
       12.53, 12.52, 12.51, 12.51, 12.47, 12.45, 12.43, 12.42, 12.42,
       12.42, 12.37,

In [48]:
#to sort the entire dataset
np.argsort(alcohol)

 

array([115, 113, 120, 110, 121, 109,  94,  88,  87,  75, 112, 127,  96,
       103, 116,  84,  77, 124,  74, 119,  91,  80, 129, 125,  82, 114,
        89,  90, 100,  86,  64, 170,  69, 108, 144, 136, 106,  97,  70,
        93,  99,  60,  78, 102, 160,  67,  65,  63,  98, 128,  59, 105,
       122, 117, 126, 157,  95, 104, 134, 111, 137, 154, 135, 101,  61,
        85,  92,  79, 133, 107,  81, 171, 118, 151, 132, 167, 139,  23,
       162, 130, 147, 131,  21, 140, 163,  73,  76, 123,  44,  25,  83,
        37,  50,  38, 149,  66, 152, 145,   2, 176, 155,   1, 153,   4,
        43, 175,  36,  57,  27, 148,  68, 141,  26, 174, 169,  41, 166,
       159,  35, 138,  72, 150,  24,  34, 142,  55,  40,  31, 168, 143,
        15,  19,  62,  32, 161,  22, 173,  58,  30, 165,  54,  12,  33,
        53, 164,  52,  51,  17, 156,  71,   9,  28,  42, 146,  47,  49,
        29,  20,   7,  48,  10,  11, 177, 172,  18,   5,  45,  56,  39,
         0,  16, 158,   3,  46,  14,   6,  13,   8], dtype=int64

In [49]:
np.arange(1,100,3)#this is use when we want to create ranges of integers

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [51]:
#to create a range with a float value in it
np.linspace?

In [52]:
#reshapping an array
from sklearn.datasets import load_digits

In [53]:
data_bunch_digits = load_digits()

In [54]:
digits_data = data_bunch_digits['data']

In [55]:
digits_data.shape

(1797, 64)

In [56]:
digits_data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])